### ISSUE TITLE
Who built/maintains the lacity ArcGIS Rest Services?

### ISSUE THREAD

**Issue by michaelkirk** [compilerla/los-angeles-data-sources#1]
Thanks for tracking these! Do you have any idea who maintains the "City of Los Angeles ArcGIS REST Services Directory"? 

I'm interested in trying to get some more things added there.

Thanks for any help!

**Comment by vykster** [comment]
Hey @michaelkirk! I get too many GitHub notifications, I missed this! I imagine you know the answer now, no?

**Comment by michaelkirk** [comment]
No actually. But I don't have an immediate need for an answer anymore. I am working on a sort of post mortem for a city project I was working on earlier this year with @lauraerinmann. I'll let you know if anything becomes of it...
